export const metadata = {
  title: 'Login',
  description: 'Generated by create next app',
  icons: {
    icon: './favIcon.png', 
  },
};

const LoginLayout = ({ children }) => {
  return children;
};

export default LoginLayout;
