export const metadata = {
    title: "Contact",
    description: "Generated by create next app",
    icons: {
      icon: "./favIcon.png", // Path inside public folder
    },
  };
  
  const ContactLayout = ({children}) => {
    return children
  }
  
  export default ContactLayout
  