export const metadata = {
    title: "Blogs",
    description: "Generated by create next app",
    icons: {
      icon: "./favIcon.png", // Path inside public folder
    },
  };
  
  const BlogLayout = ({children}) => {
    return children
  }
  
  export default BlogLayout
  