import ClientBlogLayout from "@/components/ClientBlogLayout";

export const metadata = {
  title: "Blogs",
  description: "Generated by create next app",
  icons: {
    icon: "/favIcon.png",
  },
};

export default function BlogLayout({ children }) {
  return <ClientBlogLayout>{children}</ClientBlogLayout>; 
}