import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import { Montserrat } from "next/font/google";
import { Providers } from "@/store/provider";
import UserProvider from "@/features/provider/UserProvider";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Note Book",
  description: "Generated by create next app",
  icons: {
    icon: "/favIcon.png", // Path inside public folder
  },
};

// Custom Font 
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400"], // you can add any weight you need
});



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${montserrat.className} ${geistMono.variable} bg-white text-black`}>
        <Providers>
          <UserProvider >
            <Navbar />
            {children}
            <Footer/>
          </UserProvider>
        </Providers>
      </body>
    </html>
  );
}
