export const metadata = {
  title: 'Sign Up',
  description: 'Generated by create next app',
  icons: {
    icon: './favIcon.png', // Path inside public folder
  },
};

const ResisterLayout = ({ children }) => {
  return children;
};

export default ResisterLayout;
